### ISSUE TITLE
[SUGGESTION] Disable discord integration

### ISSUE THREAD

**Issue by DhalEynn** [RedSparr0w/Pokeclicker-desktop#8]
Hello RedSparr0w, and first, thanks for the desktop app of pokeclicker.

However, I personally dislike the discord integration of the desktop app, since I prefer to have other games shown on it.
Would it be possible to add a option in the settings to stop showing the text (unless it's already here and I didn't see it?) ?

Thanks in advance.

**Comment by RedSparr0w** [comment]
Available in next release 👍
